import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:supabase_flutter/supabase_flutter.dart';

class ApiService {
  static const String baseUrl = 'https://gsvowvzdxphlguclawur.supabase.co/rest/v1';
  static const String supabaseAnonKey = "sb_publishable_vuHhBKjf4kJJgPnkFlNm9A_ErI2gVd_";

  static Uri _uri(String path, [Map<String, String>? query]) {
    String cleanPath = path.startsWith('/') ? path : '/$path';
    if (cleanPath.endsWith('/')) {
      cleanPath = cleanPath.substring(0, cleanPath.length - 1);
    }
    return Uri.parse('$baseUrl$cleanPath').replace(queryParameters: query);
  }

  /// Returns headers with the authenticated user's JWT when a session exists,
  /// falling back to the anon key for unauthenticated (public-read) requests.
  static Map<String, String> get _authHeaders {
    final session = Supabase.instance.client.auth.currentSession;
    final token = session?.accessToken ?? supabaseAnonKey;
    if (session == null) {
      debugPrint('⚠️  [ApiService] No active session — using anon key. RLS write policies will block inserts.');
    }
    return {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'apikey': supabaseAnonKey,
      'Authorization': 'Bearer $token',
      'Prefer': 'return=representation',
    };
  }

  static dynamic _handleResponse(http.Response res, {bool isListRequest = false}) {
    debugPrint("📡 [API] ${res.request?.method} ${res.request?.url} → ${res.statusCode}");
    if (res.body.isNotEmpty) debugPrint("   Body: ${res.body.length > 400 ? '${res.body.substring(0, 400)}…' : res.body}");

    if (res.statusCode >= 200 && res.statusCode < 300) {
      if (res.body.isEmpty) return isListRequest ? [] : null;
      final decoded = jsonDecode(res.body);

      if (isListRequest) {
        return decoded is List ? decoded : [decoded];
      } else {
        if (decoded is List && decoded.isNotEmpty) return decoded.first;
        return decoded;
      }
    } else {
      throw ApiException(
        statusCode: res.statusCode,
        message: res.body,
        url: res.request?.url.toString(),
      );
    }
  }

  // ═══════════════════════════════════════════════════════════════
  //  FETCH METHODS
  // ═══════════════════════════════════════════════════════════════

  /// Fetch all tournaments. Table name is TOURNAMENTS (uppercase) to match Supabase schema.
  static Future<List<dynamic>> fetchTournaments() async =>
      _handleResponse(await http.get(_uri('TOURNAMENTS'), headers: _authHeaders), isListRequest: true);

  /// Alias used by api_test_page.dart.
  static Future<List<dynamic>> getTournaments() => fetchTournaments();

  static Future<List<dynamic>> fetchTeams() async =>
      _handleResponse(await http.get(_uri('TEAMS'), headers: _authHeaders), isListRequest: true);

  static Future<List<dynamic>> fetchMatches() async =>
      _handleResponse(await http.get(_uri('MATCHES'), headers: _authHeaders), isListRequest: true);

  static Future<List<dynamic>> getAllPlayers() async =>
      _handleResponse(await http.get(_uri('PLAYERS'), headers: _authHeaders), isListRequest: true);

  static Future<List<dynamic>> fetchPlayerMatchStats() async =>
      _handleResponse(await http.get(_uri('PLAYER_MATCH_STATS'), headers: _authHeaders), isListRequest: true);

  static Future<List<dynamic>> fetchTeamMatchStats() async =>
      _handleResponse(await http.get(_uri('TEAM_MATCH_STATS'), headers: _authHeaders), isListRequest: true);

  // ═══════════════════════════════════════════════════════════════
  //  USER & AUTH
  // ═══════════════════════════════════════════════════════════════

  static Future<Map<String, dynamic>?> fetchUserData(String email) async {
    try {
      final resUser = await http.get(_uri('USERS', {'email': 'eq.$email'}), headers: _authHeaders);
      final users = _handleResponse(resUser, isListRequest: true);
      if (users is List && users.isNotEmpty) return {...users.first, 'role': 'user'};

      final resPlayer = await http.get(_uri('PLAYERS', {'email': 'eq.$email'}), headers: _authHeaders);
      final players = _handleResponse(resPlayer, isListRequest: true);
      if (players is List && players.isNotEmpty) return {...players.first, 'role': 'player'};
    } catch (e) {
      debugPrint('⚠️  [ApiService] fetchUserData error: $e');
    }
    return null;
  }

  /// Creates a row in USERS tied to the currently authenticated Supabase user.
  /// The auto-identity `user_id` (bigint) is generated by Postgres.
  /// `auth_uid` stores the Supabase auth UUID so RLS can enforce ownership.
  static Future<Map<String, dynamic>> createUser({
    required String name,
    required String email,
    required String nationality,
    required String phoneNumber,
  }) async {
    final authUser = Supabase.instance.client.auth.currentUser;
    if (authUser == null) {
      throw Exception('[createUser] No authenticated user. Cannot insert into USERS.');
    }
    debugPrint('🔐 [createUser] auth_uid = ${authUser.id}');

    return _handleResponse(
      await http.post(
        _uri('USERS'),
        headers: _authHeaders,
        body: jsonEncode({
          'name': name,
          'email': email,
          'nationality': nationality,
          'phone_number': phoneNumber,
          'auth_uid': authUser.id, // links this row to the Supabase auth user
        }),
      ),
    );
  }

  // ═══════════════════════════════════════════════════════════════
  //  CREATION METHODS
  // ═══════════════════════════════════════════════════════════════

  /// Creates a row in TOURNAMENTS (uppercase table name).
  static Future<Map<String, dynamic>> createTournament({
    required String name,
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    return _handleResponse(
      await http.post(
        _uri('TOURNAMENTS'), // ← was 'tournaments' (lowercase) — fixed
        headers: _authHeaders,
        body: jsonEncode({
          'tournament_name': name,
          'start_date': startDate.toUtc().toIso8601String(),
          'end_date': endDate.toUtc().toIso8601String(),
        }),
      ),
    );
  }

  static Future<Map<String, dynamic>> createTeam({
    required String name,
    required String logo,
    required String primaryColor,
    required String secondaryColor,
    required String goalkeeperColor,
  }) async {
    return _handleResponse(
      await http.post(
        _uri('TEAMS'),
        headers: _authHeaders,
        body: jsonEncode({
          'team_name': name,
          'logo_url': logo,
          'primary_tshirt_colors': primaryColor,
          'secondary_tshirt_colors': secondaryColor,
          'goalkeeper_tshirt_colors': goalkeeperColor,
        }),
      ),
    );
  }

  /// Creates a row in PLAYERS tied to the currently authenticated Supabase user.
  /// `auth_uid` stores the Supabase auth UUID so RLS can enforce ownership.
  static Future<Map<String, dynamic>> createPlayer({
    required String fullName,
    required int jerseyNumber,
    required String nationality,
    required double height,
    required double weight,
    required String position,
    required String email,
    required String phoneNumber,
    dynamic teamId,
  }) async {
    final authUser = Supabase.instance.client.auth.currentUser;
    if (authUser == null) {
      throw Exception('[createPlayer] No authenticated user. Cannot insert into PLAYERS.');
    }
    debugPrint('🔐 [createPlayer] auth_uid = ${authUser.id}');

    return _handleResponse(
      await http.post(
        _uri('PLAYERS'),
        headers: _authHeaders,
        body: jsonEncode({
          'full_name': fullName,
          'jersey_number': jerseyNumber,
          'nationality': nationality,
          'height': height,
          'weight': weight,
          'position': position,
          'email': email,
          'phone_number': phoneNumber,
          'auth_uid': authUser.id, // links this row to the Supabase auth user
          if (teamId != null) 'team_id': teamId,
        }),
      ),
    );
  }

  static Future<void> updatePlayer({
    required String playerId,
    int? jerseyNumber,
    dynamic teamId,
  }) async {
    _handleResponse(
      await http.patch(
        _uri('PLAYERS', {'player_id': 'eq.$playerId'}),
        headers: _authHeaders,
        body: jsonEncode({
          if (jerseyNumber != null) 'jersey_number': jerseyNumber,
          if (teamId != null) 'team_id': teamId,
        }),
      ),
    );
  }

  static Future<Map<String, dynamic>> createMatch({
    required dynamic tournamentId,
    required dynamic homeTeamId,
    required dynamic awayTeamId,
    required DateTime matchDate,
    String? videoUrl,
  }) async {
    return _handleResponse(
      await http.post(
        _uri('MATCHES'),
        headers: _authHeaders,
        body: jsonEncode({
          'tournament_id': tournamentId,
          'home_team_id': homeTeamId,
          'away_team_id': awayTeamId,
          'match_date': matchDate.toIso8601String(),
          'video_url': videoUrl ?? "",
        }),
      ),
    );
  }

  // ═══════════════════════════════════════════════════════════════
  //  STATISTICS & INVITATIONS
  // ═══════════════════════════════════════════════════════════════

  static Future<void> submitTeamMatchStats({
    required dynamic matchId,
    required dynamic teamId,
    required int goals,
    required int passes,
    required int fouls,
    required int corners,
  }) async {
    _handleResponse(
      await http.post(
        _uri('TEAM_MATCH_STATS'),
        headers: _authHeaders,
        body: jsonEncode({
          'match_id': matchId,
          'team_id': teamId,
          'goals': goals,
          'passes': passes,
          'foul': fouls,
          'corner': corners,
        }),
      ),
    );
  }

  static Future<void> submitPlayerMatchStats({
    required dynamic matchId,
    required dynamic playerId,
    required int goals,
    required int assists,
    required int yellowCard,
    required int redCard,
    required double topSpeed,
    required double totalDistance,
  }) async {
    _handleResponse(
      await http.post(
        _uri('PLAYER_MATCH_STATS'),
        headers: _authHeaders,
        body: jsonEncode({
          'match_id': matchId,
          'player_id': playerId,
          'goals': goals,
          'assists': assists,
          'yellow_card': yellowCard,
          'red_card': redCard,
          'top_speed': topSpeed,
          'total_distance': totalDistance,
        }),
      ),
    );
  }

  // Aliases for compatibility
  static Future<void> submitTeamStats({
    required dynamic matchId,
    required dynamic teamId,
    required int goals,
    required int passes,
    required int fouls,
    required int corners,
  }) => submitTeamMatchStats(
        matchId: matchId,
        teamId: teamId,
        goals: goals,
        passes: passes,
        fouls: fouls,
        corners: corners,
      );

  static Future<void> submitPlayerStats({
    required dynamic matchId,
    required dynamic playerId,
    required int goals,
    required int assists,
    required int yellowCard,
    required int redCard,
    required double topSpeed,
    required double totalDistance,
  }) => submitPlayerMatchStats(
        matchId: matchId,
        playerId: playerId,
        goals: goals,
        assists: assists,
        yellowCard: yellowCard,
        redCard: redCard,
        topSpeed: topSpeed,
        totalDistance: totalDistance,
      );

  // ═══════════════════════════════════════════════════════════════
  //  PROFILE & MEDIA
  // ═══════════════════════════════════════════════════════════════

  static Future<void> updateUserProfile({
    required String email,
    required String role,
    required Map<String, dynamic> updates,
  }) async {
    final table = role == 'player' ? 'PLAYERS' : 'USERS';
    _handleResponse(
      await http.patch(
        _uri(table, {'email': 'eq.$email'}),
        headers: _authHeaders,
        body: jsonEncode(updates),
      ),
    );
  }

  static Future<String?> uploadProfileImage(File file, String userId) async {
    try {
      final fileName = 'avatar_${userId}_${DateTime.now().millisecondsSinceEpoch}.png';
      await Supabase.instance.client.storage.from('avatars').upload(fileName, file);
      return Supabase.instance.client.storage.from('avatars').getPublicUrl(fileName);
    } catch (e) {
      debugPrint("❌ [ApiService] Upload Error: $e");
      return null;
    }
  }

  static Future<Map<String, dynamic>> sendInvitation({
    required String teamName,
    required String leagueName,
    required String playerName,
    required String playerId,
    required int jerseyNumber,
  }) async {
    return _handleResponse(
      await http.post(
        _uri('INVITATIONS'),
        headers: _authHeaders,
        body: jsonEncode({
          'team_name': teamName,
          'league_name': leagueName,
          'player_name': playerName,
          'player_id': playerId,
          'jersey_number': jerseyNumber,
          'status': 'pending',
          'timestamp': DateTime.now().toIso8601String(),
        }),
      ),
    );
  }

  static Future<void> updateInvitationStatus(String inviteId, String status) async {
    _handleResponse(
      await http.patch(
        _uri('INVITATIONS', {'invitation_id': 'eq.$inviteId'}),
        headers: _authHeaders,
        body: jsonEncode({'status': status}),
      ),
    );
  }

  static Future<bool> ping() async {
    try {
      return (await http.get(_uri('PLAYERS'), headers: _authHeaders).timeout(const Duration(seconds: 5))).statusCode == 200;
    } catch (_) {
      return false;
    }
  }
}

class ApiException implements Exception {
  final int statusCode;
  final String message;
  final String? url;

  ApiException({required this.statusCode, required this.message, this.url});

  @override
  String toString() => 'ApiException [$statusCode]${url != null ? ' at $url' : ''}: $message';
}
